/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio2.cuerpoceleste.interfaz;

import static ejercicio2.cuerpoceleste.clase.Lanzador.aniadirCuerpo;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus Bernabe Imedio Perea
 * @date 08/04/2023
 * @description Clase que hereda de JFrame para añadir cuerpos celestes
 * Tema 9 Ejercicio 2 Interfaz gráfica
 */
public class GuiAniadirCuerpo extends javax.swing.JFrame {

    //variables
    short codigo;
    String nombre;
    int diametro;
    String tipo;

    /**
     * Constructor
     */
    public GuiAniadirCuerpo() {
        initComponents();
    }
    
    
    /**
    * Sobrescribo este método para poder poner un icono personalizado
    * @return 
    */ 
   @Override
   public Image getIconImage(){
       Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("luna.png"));
       return retValue;
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAñadir = new javax.swing.JPanel();
        jTextDiametro = new javax.swing.JTextField();
        jTextCodigo = new javax.swing.JTextField();
        codigoLabel = new javax.swing.JLabel();
        diametroLabel = new javax.swing.JLabel();
        añadirGuiAni = new javax.swing.JButton();
        textoVentana = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        tipoCuerpoCombo = new javax.swing.JComboBox<>();
        nombreLabel = new javax.swing.JLabel();
        JTextNombre = new javax.swing.JTextField();
        jPanelDatosRegistro = new javax.swing.JPanel();
        jLabelAniadirResultado = new javax.swing.JLabel();
        mostrarResulLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir cuerpo celeste");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelAñadir.setBackground(new java.awt.Color(204, 204, 255));
        panelAñadir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextDiametro.setToolTipText("El diámetro debe tener 6 dígitos, recuerde los 0 a la izquierda no contabilizan");
        jTextDiametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiametroActionPerformed(evt);
            }
        });

        jTextCodigo.setToolTipText("El código debe ser de 3 digitos, los 0 a la izquierda no contabilizan");
        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });

        codigoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        codigoLabel.setText("CODIGO");

        diametroLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diametroLabel.setText("DIÁMETRO");

        añadirGuiAni.setText("Añadir");
        añadirGuiAni.setToolTipText("Añada un nuevo cuerpo celeste al fichero");
        añadirGuiAni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirGuiAniActionPerformed(evt);
            }
        });

        textoVentana.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoVentana.setText("   Añadir registro cuerpo celeste");
        textoVentana.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tipoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tipoLabel.setText("TIPO");

        tipoCuerpoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "planeta", "planetaEnano", "luna" }));
        tipoCuerpoCombo.setToolTipText("seleccione una de las 3 opciones");
        tipoCuerpoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCuerpoComboActionPerformed(evt);
            }
        });

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreLabel.setText("NOMBRE");

        JTextNombre.setToolTipText("El nombre debe tener 15 caracteres como máximo");
        JTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAñadirLayout = new javax.swing.GroupLayout(panelAñadir);
        panelAñadir.setLayout(panelAñadirLayout);
        panelAñadirLayout.setHorizontalGroup(
            panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAñadirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(textoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAñadirLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAñadirLayout.createSequentialGroup()
                        .addGroup(panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCodigo)
                            .addComponent(JTextNombre)))
                    .addGroup(panelAñadirLayout.createSequentialGroup()
                        .addGroup(panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diametroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDiametro)
                            .addComponent(tipoCuerpoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(67, 67, 67)
                .addComponent(añadirGuiAni, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelAñadirLayout.setVerticalGroup(
            panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAñadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAñadirLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAñadirLayout.createSequentialGroup()
                                .addGroup(panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tipoCuerpoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(panelAñadirLayout.createSequentialGroup()
                                .addComponent(diametroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(panelAñadirLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(añadirGuiAni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanelDatosRegistro.setBackground(new java.awt.Color(204, 153, 255));
        jPanelDatosRegistro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabelAniadirResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAniadirResultado.setText("  Datos del registro");
        jLabelAniadirResultado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mostrarResulLabel.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanelDatosRegistroLayout = new javax.swing.GroupLayout(jPanelDatosRegistro);
        jPanelDatosRegistro.setLayout(jPanelDatosRegistroLayout);
        jPanelDatosRegistroLayout.setHorizontalGroup(
            jPanelDatosRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosRegistroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDatosRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostrarResulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAniadirResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanelDatosRegistroLayout.setVerticalGroup(
            jPanelDatosRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAniadirResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(mostrarResulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelDatosRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed


    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jTextDiametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiametroActionPerformed


    }//GEN-LAST:event_jTextDiametroActionPerformed

    /**
     * Añade un cuerpo celeste
     * Recoge los datos mediante JtextField y se los pasa al método aniadirCuerpo
     * 
     * @param evt 
     */
    private void añadirGuiAniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirGuiAniActionPerformed

        try {
            //si algun campo de los jtextfield esta vacio, lanza aviso
            if (jTextCodigo.getText().equals("") || JTextNombre.getText().equals("") || jTextDiametro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo vacio");

            } else {
                
                //transformamos al formato correcto
                codigo = Short.parseShort(jTextCodigo.getText());
                nombre = JTextNombre.getText();
                tipo = String.valueOf(tipoCuerpoCombo.getSelectedItem());
                diametro = Integer.parseInt(jTextDiametro.getText());
               
                //muestro los datos del cuerpo que queremos guardar. Solo informativo, posteriormente se creará o no
                mostrarResulLabel.setText("Codigo: "+codigo+"    "+"Nombre: "+nombre+"    "+"Tipo: "+tipo+"    "+"Diametro: "+diametro);
                
                //llamo al metodo aniadirCuerpo de nuestro Lanzador para meterle los datos 
                aniadirCuerpo(codigo,nombre,tipo,diametro);//este método será el que construira el cuerpo celeste tras verificar
                
            }

        } catch (Exception e) {//esta excepción salta cuando se meten caracteres en digitos etc..
             JOptionPane.showMessageDialog(null, "Formato de datos no válido, verifique digitos y caracteres");
        }


    }//GEN-LAST:event_añadirGuiAniActionPerformed

    /**
     * Añade los item correspondientes a el tipo de objeto posible para el cuerpo celeste
     * al combo que hemos diseñado
     * @param evt 
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // opciones tipo Cuerpo Celeste
        tipoCuerpoCombo.removeAllItems();
        tipoCuerpoCombo.addItem("planeta");
        tipoCuerpoCombo.addItem("planetaEnano");
        tipoCuerpoCombo.addItem("luna");

    }//GEN-LAST:event_formWindowOpened

    private void tipoCuerpoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCuerpoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCuerpoComboActionPerformed

    private void JTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNombreActionPerformed

    }//GEN-LAST:event_JTextNombreActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextNombre;
    private javax.swing.JButton añadirGuiAni;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JLabel diametroLabel;
    private javax.swing.JLabel jLabelAniadirResultado;
    private javax.swing.JPanel jPanelDatosRegistro;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextDiametro;
    private javax.swing.JLabel mostrarResulLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelAñadir;
    private javax.swing.JLabel textoVentana;
    private javax.swing.JComboBox<String> tipoCuerpoCombo;
    private javax.swing.JLabel tipoLabel;
    // End of variables declaration//GEN-END:variables
}
