/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio2.cuerpoceleste.interfaz;

import ejercicio2.cuerpoceleste.clase.CuerpoCeleste;
import ejercicio2.cuerpoceleste.clase.Lanzador;
import static ejercicio2.cuerpoceleste.clase.Lanzador.buscarCuerpoCodigo;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus Bernabe Imedio Perea
 * @date 08/04/2023
 * @description Clase que hereda de JFrame para buscar cuerpos celestes
 * Tema 9 Ejercicio 2 Interfaz gráfica
 */
public class GuiBuscarCuerpo extends javax.swing.JFrame {

    //variables
    short buscarCodigo;
    String buscarTipoCel;

    /**
     * Constructor
     */
    public GuiBuscarCuerpo() {
        initComponents();
    }
    
    /**
    * Sobrescribo este método para poder poner un icono personalizado
    * @return 
    */ 
   @Override
   public Image getIconImage(){
       Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("luna.png"));
       return retValue;
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscarCodigo = new javax.swing.JPanel();
        jTextBuscarCodigo = new javax.swing.JTextField();
        buscarCodigoLabel = new javax.swing.JLabel();
        buscarVentana = new javax.swing.JLabel();
        buscarCodigoButton = new javax.swing.JButton();
        jPanelmostrarResultados = new javax.swing.JPanel();
        jLabelbuscarMostrar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextResultadBuscar = new javax.swing.JTextArea();
        jPanelbuscarTipo = new javax.swing.JPanel();
        buscarVentana1 = new javax.swing.JLabel();
        buscarTipoCuerpoCombo = new javax.swing.JComboBox<>();
        buscarTipoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar cuerpo celeste");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelBuscarCodigo.setBackground(new java.awt.Color(204, 204, 255));
        jPanelBuscarCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextBuscarCodigo.setToolTipText("El código debe ser de 3 digitos, los 0 a la izquierda no contabilizan");
        jTextBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarCodigoActionPerformed(evt);
            }
        });

        buscarCodigoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarCodigoLabel.setText("CODIGO");
        buscarCodigoLabel.setToolTipText("");

        buscarVentana.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarVentana.setText("  Buscar registro por código");
        buscarVentana.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        buscarCodigoButton.setText("Buscar");
        buscarCodigoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCodigoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarCodigoLayout = new javax.swing.GroupLayout(jPanelBuscarCodigo);
        jPanelBuscarCodigo.setLayout(jPanelBuscarCodigoLayout);
        jPanelBuscarCodigoLayout.setHorizontalGroup(
            jPanelBuscarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarCodigoLayout.createSequentialGroup()
                .addGroup(jPanelBuscarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarCodigoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(buscarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBuscarCodigoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanelBuscarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buscarCodigoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBuscarCodigoLayout.createSequentialGroup()
                                .addComponent(buscarCodigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelBuscarCodigoLayout.setVerticalGroup(
            jPanelBuscarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarCodigoLayout.createSequentialGroup()
                .addGroup(jPanelBuscarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarCodigoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBuscarCodigoLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanelBuscarCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarCodigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(buscarCodigoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jPanelmostrarResultados.setBackground(new java.awt.Color(204, 153, 255));
        jPanelmostrarResultados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabelbuscarMostrar.setBackground(new java.awt.Color(204, 204, 204));
        jLabelbuscarMostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelbuscarMostrar.setText("Registros encontrados");

        jTextResultadBuscar.setColumns(20);
        jTextResultadBuscar.setRows(5);
        jScrollPane2.setViewportView(jTextResultadBuscar);

        javax.swing.GroupLayout jPanelmostrarResultadosLayout = new javax.swing.GroupLayout(jPanelmostrarResultados);
        jPanelmostrarResultados.setLayout(jPanelmostrarResultadosLayout);
        jPanelmostrarResultadosLayout.setHorizontalGroup(
            jPanelmostrarResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmostrarResultadosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelbuscarMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelmostrarResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelmostrarResultadosLayout.setVerticalGroup(
            jPanelmostrarResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmostrarResultadosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelbuscarMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelbuscarTipo.setBackground(new java.awt.Color(204, 204, 255));
        jPanelbuscarTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        buscarVentana1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarVentana1.setText("   Buscar  registro por tipo");
        buscarVentana1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        buscarTipoCuerpoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "planeta", "planetaEnano", "luna" }));
        buscarTipoCuerpoCombo.setToolTipText("seleccione una de las 3 opciones");
        buscarTipoCuerpoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTipoCuerpoComboActionPerformed(evt);
            }
        });

        buscarTipoButton.setText("Buscar");
        buscarTipoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTipoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelbuscarTipoLayout = new javax.swing.GroupLayout(jPanelbuscarTipo);
        jPanelbuscarTipo.setLayout(jPanelbuscarTipoLayout);
        jPanelbuscarTipoLayout.setHorizontalGroup(
            jPanelbuscarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbuscarTipoLayout.createSequentialGroup()
                .addGroup(jPanelbuscarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelbuscarTipoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarTipoCuerpoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelbuscarTipoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(buscarVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbuscarTipoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buscarTipoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanelbuscarTipoLayout.setVerticalGroup(
            jPanelbuscarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbuscarTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(buscarTipoCuerpoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(buscarTipoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelmostrarResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelbuscarTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBuscarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelbuscarTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelmostrarResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarCodigoActionPerformed


    }//GEN-LAST:event_jTextBuscarCodigoActionPerformed

    /**
     * Añade los item correspondientes a el tipo de objeto posible para el cuerpo celeste
     * al combo que hemos diseñado
     * @param evt 
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // opciones tipo Cuerpo Celeste
        buscarTipoCuerpoCombo.removeAllItems();
        buscarTipoCuerpoCombo.addItem("planeta");
        buscarTipoCuerpoCombo.addItem("planetaEnano");
        buscarTipoCuerpoCombo.addItem("luna");

    }//GEN-LAST:event_formWindowOpened

    private void buscarTipoCuerpoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTipoCuerpoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTipoCuerpoComboActionPerformed

    /**
     * Recoge el tipo de objeto seleccionado(planeta,planetaEnano,luna, lo guarda en string y lo pasa por parámetro 
     * al método buscarCuerpoTipo para que seleccione los objetos. Nos devolvera una cadena con todos los objetos
     * que coinciden con ell tipo.
     * @param evt 
     */
    private void buscarTipoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTipoButtonActionPerformed

        
        
        
        try {
            String dataPR;
           
            //transformamos al formato correcto
            buscarTipoCel = String.valueOf(buscarTipoCuerpoCombo.getSelectedItem());
          
           //llamamos al método para guardar todos los objetos encontrados en una cadena
           dataPR=Lanzador.buscarCuerpoTipo(buscarTipoCel);
           
           //mostramos en JPANEL la cadena
            jTextResultadBuscar.setText(dataPR);
       
            
        } catch (NumberFormatException e) {//esta excepción salta cuando se meten caracteres en digitos etc..
            JOptionPane.showMessageDialog(null, "Formato de datos no válido, introduzca digitos");
        } catch (Exception ex) {
            Logger.getLogger(GuiBuscarCuerpo.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_buscarTipoButtonActionPerformed

    /**
     * Recoge el codigo del objeto a buscar y lo pasa por parámetro al metodo buscarCuerpoCodigo el cual
     * nos devolvera el objeto cuerpo celeste que coincida o nos indicará
     * en caso de que no exista
     * @param evt 
     */
    private void buscarCodigoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCodigoButtonActionPerformed

        //declaro objeto
        CuerpoCeleste cuerpocelesteencontrado;
        
        try {
            //si campo es vacio, lanzo mensaje 
            if (jTextBuscarCodigo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo vacio");

            } else {

                //transformamos al formato correcto
                buscarCodigo = Short.parseShort(jTextBuscarCodigo.getText());

                //llamo a la logica con el metodo buscar por codigo de nuestro Lanzador para meterle los datos 
                cuerpocelesteencontrado = buscarCuerpoCodigo(buscarCodigo);

                if (cuerpocelesteencontrado == null) {

                } else {
                    jTextResultadBuscar.setText(cuerpocelesteencontrado.toString());
                }

            }
            jTextBuscarCodigo.setText("");

        } catch (NumberFormatException e) {//esta excepción salta cuando se meten caracteres en digitos etc..
            JOptionPane.showMessageDialog(null, "Formato de datos no válido, introduzca digitos");
        }

    }//GEN-LAST:event_buscarCodigoButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCodigoButton;
    private javax.swing.JLabel buscarCodigoLabel;
    private javax.swing.JButton buscarTipoButton;
    private javax.swing.JComboBox<String> buscarTipoCuerpoCombo;
    private javax.swing.JLabel buscarVentana;
    private javax.swing.JLabel buscarVentana1;
    private javax.swing.JLabel jLabelbuscarMostrar;
    private javax.swing.JPanel jPanelBuscarCodigo;
    private javax.swing.JPanel jPanelbuscarTipo;
    private javax.swing.JPanel jPanelmostrarResultados;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextBuscarCodigo;
    private javax.swing.JTextArea jTextResultadBuscar;
    // End of variables declaration//GEN-END:variables
}
