/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio2.cuerpoceleste.interfaz;

import ejercicio2.cuerpoceleste.clase.CuerpoCeleste;
import ejercicio2.cuerpoceleste.clase.Lanzador;
import ejercicio2.cuerpoceleste.fichero.OperacionesConFichero;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jesus Bernabe Imedio Perea
 * @date 10/04/2023
 * @description Clase GuiTabla que hereda de JFrame, genera una tabla donde mostraremos nuestros registros
 * Tarea 9 Ejercicio 2 Interfaz gráfica
 */
public class GuiTabla extends javax.swing.JFrame {

  
    

    /**
     * Constructor
     */
    public GuiTabla() {
        initComponents();
        
        
        
        //llamamos al metodo listar
        listarTabla();
    }
    
    /**
    * Sobrescribo este método para poder poner un icono personalizado
    * @return 
    */ 
   @Override
   public Image getIconImage(){
       Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("luna.png"));
       return retValue;
   }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelmostrarCuerpos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMostrarArray = new javax.swing.JTable();
        jPaneletiqueta = new javax.swing.JPanel();
        jLabeltabla = new javax.swing.JLabel();
        jButtonSalirTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mostrar cuerpos celestes");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelmostrarCuerpos.setBackground(new java.awt.Color(204, 204, 255));
        jPanelmostrarCuerpos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTableMostrarArray.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Diametro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMostrarArray);

        javax.swing.GroupLayout jPanelmostrarCuerposLayout = new javax.swing.GroupLayout(jPanelmostrarCuerpos);
        jPanelmostrarCuerpos.setLayout(jPanelmostrarCuerposLayout);
        jPanelmostrarCuerposLayout.setHorizontalGroup(
            jPanelmostrarCuerposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmostrarCuerposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelmostrarCuerposLayout.setVerticalGroup(
            jPanelmostrarCuerposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmostrarCuerposLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPaneletiqueta.setBackground(new java.awt.Color(204, 153, 255));
        jPaneletiqueta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabeltabla.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltabla.setText("Listado del fichero");

        jButtonSalirTabla.setText("Cerrar");
        jButtonSalirTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneletiquetaLayout = new javax.swing.GroupLayout(jPaneletiqueta);
        jPaneletiqueta.setLayout(jPaneletiquetaLayout);
        jPaneletiquetaLayout.setHorizontalGroup(
            jPaneletiquetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneletiquetaLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabeltabla, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(jButtonSalirTabla)
                .addGap(38, 38, 38))
        );
        jPaneletiquetaLayout.setVerticalGroup(
            jPaneletiquetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneletiquetaLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabeltabla)
                .addGap(16, 16, 16))
            .addGroup(jPaneletiquetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSalirTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelmostrarCuerpos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPaneletiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPaneletiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelmostrarCuerpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    

    }//GEN-LAST:event_formWindowOpened
/**
 * Cierra la ventana actual, solo lo he implementado en esta clase, porque me es más cómodo salir dándole a cerrar en la
 * ventana. Lo he dejado a modo de aprendizaje por el dispose()
 * @param evt 
 */
    private void jButtonSalirTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirTablaActionPerformed

        //cerrar ventana actual, 
        this.dispose();

        
    }//GEN-LAST:event_jButtonSalirTablaActionPerformed

    /**
     * Metodo que carga los valores del arrayList cuerpos en la tabla, colocando cada valor en la fila y columna que correspona
     */
    private void listarTabla(){
        
        //llamamos al metodo listar del Lanzador(modificado), para abrir el archivo y cargar el array cuerpos
        //para que posteriormente no me muestre la tabla vacia    
        OperacionesConFichero.listarCuerpo();

        
        //Creamos objeto modelo al cual le pasamos mediante array las cabeceras de nuestras columnas y cuantas filas tendra(cuerpos.size()
        DefaultTableModel modelo =new DefaultTableModel(new String[]{"Codigo","Nombre","Tipo","Diametro"},Lanzador.cuerpos.size());
        
        //A nuestra tabla le asignamos el modelo definido anteriormente
        jTableMostrarArray.setModel(modelo);
        
        //Definimos modelo de datos
        TableModel modeloDatos=jTableMostrarArray.getModel();
        
        //llenamos modelo de datos
        for (int i = 0; i < Lanzador.cuerpos.size(); i++) {
            
            //determino posición del objeto
            CuerpoCeleste cuerpo=Lanzador.cuerpos.get(i);
            
            //meto en la tabla cada uno de los valores del objeto
            
            modeloDatos.setValueAt(cuerpo.getCodigoCuerpo(),i,0);//pongo el valor en fila i, columna0
            modeloDatos.setValueAt(cuerpo.getNombre(),i,1);//pongo el valor en fila i, columna0
            modeloDatos.setValueAt(cuerpo.getTipoObjeto(),i,2);//pongo el valor en fila i, columna0
            modeloDatos.setValueAt(cuerpo.getDiametro(),i,3);//pongo el valor en fila i, columna0
        }
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalirTabla;
    private javax.swing.JLabel jLabeltabla;
    private javax.swing.JPanel jPaneletiqueta;
    private javax.swing.JPanel jPanelmostrarCuerpos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMostrarArray;
    // End of variables declaration//GEN-END:variables
}
