/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio2.cuerpoceleste.interfaz;

import ejercicio2.cuerpoceleste.clase.Lanzador;
import ejercicio2.cuerpoceleste.fichero.OperacionesConFichero;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author jesus Bernabe Imedio Perea
 * @date 07/04/2023
 * @description Clase InterfazGui que hereda de JFrame, es la pantalla principal
 * de la aplicación Controla y lanza el acceso al resto de nuestras JFRAME
 * Tarea9 Ejercicio2 Interfaz gráficas
 */
public class InterfazGui extends javax.swing.JFrame {

    /**
     * Constructor
     */
    public InterfazGui() {
        initComponents();
 

    }

   /**
    * Sobrescribo este método para poder poner un icono personalizado
    * @return 
    */ 
   @Override
   public Image getIconImage(){
       Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("luna.png"));
       return retValue;
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSecundario = new javax.swing.JPanel();
        salirApp = new javax.swing.JButton();
        borrarFichero = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        añadirCuerpoCeleste = new javax.swing.JButton();
        buscarCuerpoCeleste = new javax.swing.JButton();
        listarCuerposCelestes = new javax.swing.JButton();
        eliminarCuerpoCeleste = new javax.swing.JButton();
        imagenApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI Cuerpos celestes");
        setIconImage(getIconImage());

        panelSecundario.setBackground(new java.awt.Color(204, 153, 255));
        panelSecundario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        salirApp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salirApp.setText("Salir");
        salirApp.setToolTipText("Sal de la aplicación cerrando todas las ventanas activas");
        salirApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirAppActionPerformed(evt);
            }
        });

        borrarFichero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        borrarFichero.setText("Borrar ");
        borrarFichero.setToolTipText("Elimina todos los cuerpos celestes que contiene el fichero");
        borrarFichero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        borrarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarFicheroActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Miriam Libre", 1, 18)); // NOI18N
        jLabelTitulo.setText("Tu App de cuerpos celestes");

        javax.swing.GroupLayout panelSecundarioLayout = new javax.swing.GroupLayout(panelSecundario);
        panelSecundario.setLayout(panelSecundarioLayout);
        panelSecundarioLayout.setHorizontalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSecundarioLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(borrarFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(50, 50, 50)
                .addComponent(salirApp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        panelSecundarioLayout.setVerticalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(borrarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(salirApp, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelPrincipal.setBackground(new java.awt.Color(204, 204, 255));
        jPanelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        añadirCuerpoCeleste.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        añadirCuerpoCeleste.setText("Añadir");
        añadirCuerpoCeleste.setToolTipText("Añadir un cuerpo celeste");
        añadirCuerpoCeleste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirCuerpoCelesteActionPerformed(evt);
            }
        });

        buscarCuerpoCeleste.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buscarCuerpoCeleste.setText("Buscar");
        buscarCuerpoCeleste.setToolTipText("Buscar un cuerpo celeste");
        buscarCuerpoCeleste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCuerpoCelesteActionPerformed(evt);
            }
        });

        listarCuerposCelestes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listarCuerposCelestes.setText("Listar");
        listarCuerposCelestes.setToolTipText("Lista los cuerpos celestes según tipo");
        listarCuerposCelestes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCuerposCelestesActionPerformed(evt);
            }
        });

        eliminarCuerpoCeleste.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminarCuerpoCeleste.setText("Eliminar");
        eliminarCuerpoCeleste.setToolTipText("Elimina un cuerpo celeste");
        eliminarCuerpoCeleste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCuerpoCelesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(añadirCuerpoCeleste, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarCuerpoCeleste, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listarCuerposCelestes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarCuerpoCeleste, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añadirCuerpoCeleste, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCuerpoCeleste, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listarCuerposCelestes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarCuerpoCeleste, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imagenApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2/cuerpoceleste/imagenes/recorte2celestevioleta.jpg"))); // NOI18N
        imagenApp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelSecundario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imagenApp, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imagenApp, javax.swing.GroupLayout.PREFERRED_SIZE, 413, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Solicita el codigo del cuerpo celeste mediante un JoptionPane y llama al
     * método eliminarCuerpo
     *
     * @param evt
     */
    private void eliminarCuerpoCelesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCuerpoCelesteActionPerformed
        try {
            String codigo;
            //solicitamos codigo por dialogo
            codigo = JOptionPane.showInputDialog("Introduzca el código a eliminar");

            //pasamos a short
            short codi = Short.parseShort(codigo);

            //llamo a metodo eliminar
            Lanzador.eliminarCuerpo(codi);

        } catch (NumberFormatException e) {//esta excepción salta cuando se meten caracteres en digitos etc..
            JOptionPane.showMessageDialog(null, "Formato de datos no válido, introduzca digitos");
        }

    }//GEN-LAST:event_eliminarCuerpoCelesteActionPerformed
    /**
     * Lanzo la ventana del JFrame GuTabla
     *
     * @param evt
     */
    private void listarCuerposCelestesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCuerposCelestesActionPerformed

        try {

            //creo objeto de GuiTabla y lanzo su ventana
            GuiTabla ventanaTabla = new GuiTabla();
            ventanaTabla.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            ventanaTabla.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(InterfazGui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_listarCuerposCelestesActionPerformed

    /**
     * Lanzo la ventana del JFrame Añadir
     *
     * @param evt
     */
    private void añadirCuerpoCelesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirCuerpoCelesteActionPerformed
        try {

            //creo objeto de GuiAniadirCuerpo y lanzo su ventana
            GuiAniadirCuerpo ventana = new GuiAniadirCuerpo();
            ventana.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(InterfazGui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_añadirCuerpoCelesteActionPerformed

    /**
     * Lanzo la ventana del JFrame buscarCuerpos
     *
     * @param evt
     */
    private void buscarCuerpoCelesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCuerpoCelesteActionPerformed
        try {

            //creo objeto de GuiBuscarCuerpo y lanzo su ventana
            GuiBuscarCuerpo ventanaBuscar = new GuiBuscarCuerpo();
            //determinamos que cuando demos a cerrar ventana, solo se cierre esta no todas las demás
            ventanaBuscar.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            //indicamos que se visualice la ventana
            ventanaBuscar.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(InterfazGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarCuerpoCelesteActionPerformed

    /**
     * Salir de la aplicación, este método elimina al implementado en la
     * practica 6 puesto que lo hace con un JoptionPane
     *
     * @param evt
     */
    private void salirAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirAppActionPerformed

        //recogemos respuesta
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);

        //recojemos datos del dialigo y comparamos
        if (respuesta == JOptionPane.NO_OPTION) {

        } else {
            //cerramos todas las pantallas activas
            System.exit(0);
        }

    }//GEN-LAST:event_salirAppActionPerformed

    /**
     * Borrar el fichero llamando al método eliminarFichero
     *
     * @param evt
     */
    private void borrarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarFicheroActionPerformed

        //recogemos respuesta
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que desea eliminar el contenido del fichero?", "Eliminar fichero", JOptionPane.YES_NO_OPTION);

        //recojemos datos del dialigo y comparamos
        if (respuesta == JOptionPane.NO_OPTION) {

        } else {

            //uso metodo eliminar fichero
            OperacionesConFichero.eliminarFichero();

        }


    }//GEN-LAST:event_borrarFicheroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirCuerpoCeleste;
    private javax.swing.JButton borrarFichero;
    private javax.swing.JButton buscarCuerpoCeleste;
    private javax.swing.JButton eliminarCuerpoCeleste;
    private javax.swing.JLabel imagenApp;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JButton listarCuerposCelestes;
    private javax.swing.JPanel panelSecundario;
    private javax.swing.JButton salirApp;
    // End of variables declaration//GEN-END:variables
}
