/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio1.calculadora;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author jesus Bernabe Imedio Perea
 * @date 03/04/2023
 * @description JFrame Calculadora Tema 9 Ejericio 1 Interfaces
 */
public class Calculadora extends javax.swing.JFrame {

    // variables operandos para realizar las operaciones
    public float operando1;
    public float operando2;

    //variable operador
    public String operador;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }
    
    

    /**
     * Sobrescribo este método para poder poner un icono personalizado
     *
     * @return
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("calculadora.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSecundario = new javax.swing.JPanel();
        resultado = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        numero9 = new javax.swing.JButton();
        numero8 = new javax.swing.JButton();
        numero7 = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        numero6 = new javax.swing.JButton();
        numero5 = new javax.swing.JButton();
        numero4 = new javax.swing.JButton();
        numero3 = new javax.swing.JButton();
        numero2 = new javax.swing.JButton();
        numero1 = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        operarador_punto = new javax.swing.JButton();
        numero0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(51, 204, 255));
        setIconImage(getIconImage());
        setResizable(false);

        panelSecundario.setBackground(new java.awt.Color(204, 204, 204));
        panelSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultado.setBackground(new java.awt.Color(255, 255, 255));
        resultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultado.setToolTipText("muestra resultado");
        resultado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        resultado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        resultado.setOpaque(true);
        panelSecundario.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 15, 222, 56));

        cancelar.setText("C");
        cancelar.setToolTipText("limpia pantalla");
        cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        panelSecundario.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 89, 42, 42));

        multiplicar.setText("*");
        multiplicar.setToolTipText("multiplicación");
        multiplicar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });
        panelSecundario.add(multiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 89, 42, 42));

        restar.setText("-");
        restar.setToolTipText("restar");
        restar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });
        panelSecundario.add(restar, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 89, 42, 42));

        dividir.setText("/");
        dividir.setToolTipText("división");
        dividir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });
        panelSecundario.add(dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 89, 42, 42));

        numero9.setText("9");
        numero9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero9ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 149, 42, 42));

        numero8.setText("8");
        numero8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero8ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 149, 42, 42));

        numero7.setText("7");
        numero7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero7ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 149, 42, 42));

        sumar.setText("+");
        sumar.setToolTipText("sumar");
        sumar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });
        panelSecundario.add(sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 149, 42, 102));

        numero6.setText("6");
        numero6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero6ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 209, 42, 42));

        numero5.setText("5");
        numero5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero5ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 209, 42, 42));

        numero4.setText("4");
        numero4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero4ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 209, 42, 42));

        numero3.setText("3");
        numero3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero3ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 269, 42, 42));

        numero2.setText("2");
        numero2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 269, 42, 42));

        numero1.setText("1");
        numero1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 269, 42, 42));

        igual.setText("=");
        igual.setToolTipText("muestra el resultado");
        igual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        panelSecundario.add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 269, 42, 102));
        igual.getAccessibleContext().setAccessibleDescription("");

        operarador_punto.setText(".");
        operarador_punto.setToolTipText("números con decimales");
        operarador_punto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        operarador_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operarador_puntoActionPerformed(evt);
            }
        });
        panelSecundario.add(operarador_punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 329, 42, 42));

        numero0.setText("0");
        numero0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        numero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero0ActionPerformed(evt);
            }
        });
        panelSecundario.add(numero0, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 329, 102, 42));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSecundario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed

        // control para que no salte excepción si pulso directamente el boton restar
        if (this.resultado.getText() == "") {

        } else {

            this.operando1 = Float.parseFloat(this.resultado.getText());//asignamos valor de resultado al operando 1
            this.operador = "-";//asignamos el operador - al operador
            this.resultado.setText("");//borramos el resultado
        }
    }//GEN-LAST:event_restarActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        
    
        if (this.resultado.getText() == "") {

        } else {

            this.operando1 = Float.parseFloat(this.resultado.getText());//asignamos valor de resultado al operando 1
            this.operador = "/";//asignamos el operador / a operador
            this.resultado.setText("");//borramos el resultado
        }


    }//GEN-LAST:event_dividirActionPerformed

    private void numero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero8ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 8 
        this.resultado.setText(this.resultado.getText() + "8");
    }//GEN-LAST:event_numero8ActionPerformed

    private void numero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero5ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 5
        this.resultado.setText(this.resultado.getText() + "5");
    }//GEN-LAST:event_numero5ActionPerformed

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 2
        this.resultado.setText(this.resultado.getText() + "2");
    }//GEN-LAST:event_numero2ActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed

        if (this.resultado.getText() == "") {//impedimos que salte la excepcion al intentar poner un = al principio

        } else {

            this.operando2 = Float.parseFloat(this.resultado.getText());//asignamos valor de resultado al operando 2

            //en funcion del operador
            switch (this.operador) {

                case "+":
                    this.resultado.setText(quitarCero(this.operando1 + this.operando2));//sumo los 2 operandos y los convierto a String asignandolo a resultao

                    break;
                case "-":
                    this.resultado.setText(quitarCero(this.operando1 - this.operando2));//resto los 2 operandos y los convierto a String asignandolo a resultao

                    break;
                case "*":
                    this.resultado.setText(quitarCero(this.operando1 * this.operando2));//multiplico los 2 operandos y los convierto a String asignandolo a resultao

                    break;
                case "/":// controlo que no se pueda dividir por 0
                    
                    if (this.operando2 == 0) {
                        this.resultado.setText("No podemos / por cero  ");
                    } else {
                        this.resultado.setText(quitarCero(this.operando1 / this.operando2));//divido los 2 operandos y los convierto a String asignandolo a resultao
                    }

                    break;

            }

        }


    }//GEN-LAST:event_igualActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed

        //controlo que no salte excepcion al pulsar directamente el / sin poner operando antes
        if (this.resultado.getText() == "") {

        } else {

            this.operando1 = Float.parseFloat(this.resultado.getText());//asignamos valor de resultado al operando 1
            this.operador = "+";//asignamos el operador + a operador
            this.resultado.setText("");//borramos el resultado
        }
    }//GEN-LAST:event_sumarActionPerformed

    private void numero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero6ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 6
        this.resultado.setText(this.resultado.getText() + "6");
    }//GEN-LAST:event_numero6ActionPerformed

    private void numero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero3ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 3
        this.resultado.setText(this.resultado.getText() + "3");
    }//GEN-LAST:event_numero3ActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed

        //control para que no salte excepción si intento multiplizar sin haber seleccionado operando
        if (this.resultado.getText() == "") {

        } else {

            this.operando1 = Float.parseFloat(this.resultado.getText());//asignamos valor de resultado al operando 1
            this.operador = "*";//asignamos el operador * a operador
            this.resultado.setText("");//borramos el resultado
        }
    }//GEN-LAST:event_multiplicarActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 1 
        this.resultado.setText(this.resultado.getText() + "1");
    }//GEN-LAST:event_numero1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // limpiamos resultado
        this.resultado.setText("");

    }//GEN-LAST:event_cancelarActionPerformed

    private void numero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero0ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 0 
        this.resultado.setText(this.resultado.getText() + "0");
    }//GEN-LAST:event_numero0ActionPerformed

    private void numero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero4ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 4
        this.resultado.setText(this.resultado.getText() + "4");
    }//GEN-LAST:event_numero4ActionPerformed

    private void numero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero9ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 9
        this.resultado.setText(this.resultado.getText() + "9");
    }//GEN-LAST:event_numero9ActionPerformed

    private void numero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero7ActionPerformed
        // primero capturamos con getText el valor de resultado y concatenamos con 7 
        this.resultado.setText(this.resultado.getText() + "7");
    }//GEN-LAST:event_numero7ActionPerformed

    private void operarador_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operarador_puntoActionPerformed

        //CNONTROLAR QUE NO SE PUEDA PONER UN PUNTO
        if (this.resultado.getText() == "") {//para no poner un . al principio

        } else {
            if (!this.resultado.getText().contains(".")) {// si no contiene un . ya esta en resultado
                this.resultado.setText(this.resultado.getText() + ".");
            } else {
                //no pone el . si ya existe en la cadena
            }

        }


    }//GEN-LAST:event_operarador_puntoActionPerformed

    /**
     * Metodo para quita el .0 en caso de que el resultado sea entero.
     *
     * @param resultado
     * @return
     */
    private String quitarCero(float resultado) {
        String retorno = "";
        retorno = Float.toString(resultado);

        if (resultado % 1 == 0) { //si resto es 0
            return retorno.substring(0, retorno.length() - 2);//quito 2 caracteres
        } else {
            return retorno;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton dividir;
    private javax.swing.JButton igual;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton numero0;
    private javax.swing.JButton numero1;
    private javax.swing.JButton numero2;
    private javax.swing.JButton numero3;
    private javax.swing.JButton numero4;
    private javax.swing.JButton numero5;
    private javax.swing.JButton numero6;
    private javax.swing.JButton numero7;
    private javax.swing.JButton numero8;
    private javax.swing.JButton numero9;
    private javax.swing.JButton operarador_punto;
    private javax.swing.JPanel panelSecundario;
    private javax.swing.JButton restar;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
